# Generated by Django 5.0 on 2023-12-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
    ]
